# 질병 선택 콤보박스
        self.disease_combo = QComboBox(self)
        self.disease_combo.addItem("간질환")
        self.disease_combo.addItem("갑상선")
        self.disease_combo.addItem("고혈압")
        self.disease_combo.addItem("골다공증")
        self.disease_combo.addItem("관절염")
        self.disease_combo.addItem("노인성 빈혈")
        self.disease_combo.addItem("노인성 우울증")
        self.disease_combo.addItem("녹내장")
        self.disease_combo.addItem("뇌동맥류")
        self.disease_combo.addItem("노졸증")
        self.disease_combo.addItem("당뇨병")
        self.disease_combo.addItem("동맥경화증")
        self.disease_combo.addItem("변비")
        self.disease_combo.addItem("신장병")
        self.disease_combo.addItem("오십견")
        self.disease_combo.addItem("요통")
        self.disease_combo.addItem("위장병")
        self.disease_combo.addItem("치매")
        self.disease_combo.addItem("통풍")
        self.disease_combo.addItem("퇴행성 근골격장애")
        self.disease_combo.addItem("파킨슨병")
        self.disease_combo.currentTextChanged.connect(self.update_title_and_load_text)

